### ISSUE TITLE
redux-immutable-state-invariant

### ISSUE THREAD

**Issue by samuxyz** [zushenyan/Workstation#3]
I was wondering why you installed it as dev-dependency, as we actively import it in our codebase~

**Comment by zushenyan** [comment]
<strike>Must be installed mistakenly. >_></strike>

If I understand what `redux-immutable-state-invariant` said on its official page correctly, it is for development only, which means it won't be bundled in production.

**Comment by samuxyz** [comment]
sorry i didnt see you only add it in development.
