### ISSUE TITLE
redux-logger

### ISSUE THREAD

**Issue by samuxyz** [zushenyan/Workstation#5]
I personally hate it coz it dirts my console and when i log something else it's hard to trace my stuff so i removed it from flw and rg2. The devtools is enough for me. What do you think? Do you think it's necessary?

**Comment by zushenyan** [comment]
I agree on the `dirt console` part, but when debugging on other browsers (especially IE), we still need a basic logging tool for inspecting what's happening.

**Comment by samuxyz** [comment]
damn IE...
